---
- name: install trendmicro
  include_role:
    name: install_trendmicro

- name: install crowdstrike
  include_role:
    name: install_crowdstrike

- name: install rapid7 agent
  include_role:
    name: install_rapid7