FROM nginx:latest as server

RUN mkdir -p /usr/share/nginx/html \
    && apt-get update \
    && apt-get install --no-install-recommends --no-install-suggests -y apt-transport-https wget gnupg \
    && wget -qO - https://apt.signalsciences.net/release/gpgkey | apt-key add - \
    && echo "deb https://apt.signalsciences.net/release/debian/ buster main" >> /etc/apt/sources.list.d/sigsci-release.list \
    && apt-get update \
    && apt-get install --no-install-recommends --no-install-suggests -y sigsci-agent \
    && mkdir -p /etc/sigsci \
    && touch /etc/sigsci/agent.conf \
    && echo 'accesskeyid="{{ sigsci_agent.access_key_id }}"\nsecretaccesskey="{{ sigsci_agent.secret_access_key }}"\nserver-hostname="{{ sigsci_agent.server_hostname }}"' >> /etc/sigsci/agent.conf \
    && apt-get install --no-install-recommends --no-install-suggests -y supervisor \
    && mkdir -p /var/log/supervisor \
    && export NGINX_VERSION=$(nginx -v 2>&1 | sed "s/^.*\///") \
    && apt-get install --no-install-recommends --no-install-suggests -y nginx-module-sigsci-nxo=${NGINX_VERSION}* \
    && sed -i "8i load_module /etc/nginx/modules/ngx_http_sigsci_module.so;" /etc/nginx/nginx.conf

COPY ./supervisord.conf /etc/supervisor/conf.d/
COPY ./default.conf /etc/nginx/conf.d/
CMD ["/usr/bin/supervisord"]